#%RAML 1.0 DataType
type: object
properties:
  tripCancel: string
  tripInterrupt: string
  emergencyMedical: string
  emergencyMedicalTransport: string
  baggageLoss: string
  travelDelay: string
  hotlineAssistance: string
  totalTripCost: string
  RentalCarDamageProtector: string
  PremiumPaid: string