#%RAML 1.0 DataType
type: object
properties:
  policyNumber: string
  travelPlan: string
  newPremiumCal: string
  coverageAmt: string
  destination: string
  fromDate: string
  toDate: string
  tripCost: string
  travellerOneAge: string
  travellerTwoAge: string
  travellerThreeAge: string
  residence: string
  totalPremium: string