#%RAML 1.0 NamedExample
value:
  policyNumber: US-IND-1290992
  travelPlan: Two Trip Premium
  destination: India
  travelFromDate: 05-1-2023
  travelToDate: 12-1-2023
  totalTripCost: $18000
  premiumPaid: $800
  travellerList: [
    {
      firstName: Traveller1-John,
      lastName: Traveller1- Ronaldo,
      age: 35,
      email: JohnRonaldo@abc.com,
      stateName: New York,
      address: Mr John Smith. 132 My Street Kingston New York 12401
    },
    {
      firstName: Traveller2-Michael,
      lastName: Traveller2- Smith,
      age: 40,
      email: MichaelSmith@abc.com,
      stateName: New York,
      address: 47 W 13th St New York NY 10011 USA
    }
  ]
  coverageList: [
    {
      coverageDesc: Trip Cancellation,
      coverageAmt: $9000
    },
    { 
      coverageDesc: Trip Interruption,
      coverageAmt: $7000
    },
    {
      coverageDesc: Emergency Medical,
      coverageAmt: $11000
    },
    {
      coverageDesc: Emergency Medical Transportation,
      coverageAmt: $40000
    },
    {
      coverageDesc: Baggage Loss/Damage,
      coverageAmt: $800
    },
    {
      coverageDesc: Travel Delay,
      coverageAmt: $200
    },
    {
      coverageDesc: 24-Hr Hotline Assistance,
      coverageAmt: $0
    },
    {
      coverageDesc: Rental Car Damage Protector,
      coverageAmt: $90
    }
  ]