#%RAML 1.0 NamedExample
value:
  policyNumber: US-CN-1290991
  travelPlan: One Trip Basic
  newPremiumCal: $771
  coverageAmt: $154
  destination: One Trip Basic
  fromDate: 15-10-2022
  toDate: 28-10-2022
  tripCost: $20000
  travellerOneAge: "42"
  travellerTwoAge: "45"
  travellerThreeAge: "23"
  residence: New York
  totalPremium: $925