#%RAML 1.0 NamedExample
value:
  oldPlanBenfits:
    tripCancel: $8000
    tripInterrupt: $8000
    emergencyMedical: $10000
    emergencyMedicalTransport: $50000
    baggageLoss: $500
    travelDelay: $300
    hotlineAssistance: Included
    totalTripCost: $15000
    RentalCarDamageProtector: $0
    PremiumPaid: $590
  newPlanBenfits: 
    tripCancel: $7000
    tripInterrupt: $7000
    emergencyMedical: $10000
    emergencyMedicalTransport: $50000
    baggageLoss: $500
    travelDelay: $300
    hotlineAssistance: Included
    totalTripCost: $15000
    RentalCarDamageProtector: $154
    PremiumPaid: $771