#%RAML 1.0
title: InsuranceAPI

types:
  Trip: !include datatypes/tripdataType.raml
  Insurance: !include datatypes/insurancedataType.raml
  NewPolicy: !include datatypes/newpolicydataType.raml
  PlanBenefits: !include datatypes/planbenefitsdataType.raml

/api:
  /login:
    get:
      responses:
        200:
          body:
            application/json:
              example:
                message: Login success
        401:
          body:
            application/json:
              example:
                message: Invalid credentials
  
  /insurance:
    /tripList:
      get:
        responses:
          200:
            body:
              application/json:
                type: Trip[]
                example: !include examples/tripListExample.raml
          404:
            body:
              application/json:
                example:
                  message: No trips found
  
    get:
      responses:
        200:
          body:
            application/json:
              type: Insurance
              example: !include examples/insuranceExample.raml
        404:
          body:
            application/json:
              example:
                message: No insurance policy found
  
    put:
      body:
        application/json:
          type: Insurance
          example: !include examples/insuranceExample.raml
      responses:
        200:
          body:
            application/json:
              example: 
                message: Insurance policy updated
        404:
          body:
            application/json:
              example:
                message: Insurance policy does not exist

    /dui:
      post:
        responses:
          200:
            body:
              application/json:
                example:
                  message: DUI check is success for traveller
          400:
            body:
              application/json:
                example:
                  message: DUI check unsuccessful
  
    /policyPdf:
      get:
        responses:
          200:
            body:
              application/json:
                example:
                  message: Policy PDF downloaded
          404:
            body:
              application/json:
                example:
                  message: Policy not found
  
    /paymentGateway:
      post:
        responses:
          200:
            body:
              application/json:
                example:
                  message: Payment success
          400:
            body:
              application/json:
                example:
                  message: Payment unsuccessful

    /newPolicy:
      get:
        responses:
          200:
            body:
              application/json:
                type: NewPolicy
                example: !include examples/newPolicyExample.raml
          404:
            body:
              application/json:
                example:
                  message: New policy not found

    /newQuote:
      get:
        responses:
          200:
            body:
              application/json:
                type: PlanBenefits
                example: !include examples/planBenefitsExample.raml
          404:
            body:
              application/json:
                example:
                  message: New quote not found